### ISSUE TITLE
eas-build-on-success fails only on iOS

### ISSUE THREAD

**Issue by florentpergoud** [thalmann-christof/eas-meastro-setup#1]
Hi ! 
I followed your tutorial and ended up with : 
- Android Maestro tests running, passing in `https://console.mobile.dev/`
- iOS `eas-build-on-success` failing on o this error before uploading to   `https://console.mobile.dev/` : 
```
==> openjdk
For the system Java wrappers to find this JDK, symlink it with
  sudo ln -sfn /opt/homebrew/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
openjdk is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS provides similar software and installing this software in
parallel can cause all kinds of trouble.
If you need to have openjdk first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"' >> ~/.zshrc
For compilers to find openjdk you may need to set:
  export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include"
[stderr] 
+ echo 'export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"'
[stderr] 
+ sudo ln -sfn /opt/homebrew/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
[stderr] 
+ export CPPFLAGS=-I/opt/homebrew/opt/openjdk/include
[stderr] 
+ CPPFLAGS=-I/opt/homebrew/opt/openjdk/include
[stderr] 
+ APP_EXECUTABLE_PATH=/Users/expo/workingdir/build/ios/build/Build/Products/Release-iphonesimulator/MaestroEasExample.app
[stderr] 
+ MAESTRO_API_KEY=************************************
[stderr] 
+ maestro cloud --apiKey ************************************ /Users/expo/workingdir/build/ios/build/Build/Products/Release-iphonesimulator/MaestroEasExample.app maestro/test.yaml
Uploading Flow(s)...
[stderr] 
java.io.FileNotFoundException: /Users/expo/workingdir/build/ios/build/Build/Products/Release-iphonesimulator/MaestroEasExample.app
[stderr] 
	at org.rauschig.jarchivelib.CommonsArchiver.writeToArchive(CommonsArchiver.java:225)
[stderr] 
	at org.rauschig.jarchivelib.CommonsArchiver.create(CommonsArchiver.java:63)
[stderr] 
	at maestro.cli.cloud.CloudInteractor.upload(CloudInteractor.kt:85)
[stderr] 
	at maestro.cli.command.CloudCommand.call(CloudCommand.kt:131)
[stderr] 
	at maestro.cli.command.CloudCommand.call(CloudCommand.kt:32)
[stderr] 
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
[stderr] 
	at picocli.CommandLine.access$1200(CommandLine.java:145)
[stderr] 
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
[stderr] 
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
[stderr] 
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
[stderr] 
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
[stderr] 
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
[stderr] 
	at picocli.CommandLine.execute(CommandLine.java:2058)
[stderr] 
	at maestro.cli.AppKt.main(App.kt:136)
[stderr] 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Here is my `eas-build.yaml` 
```

name: EAS Builds
on:
  push:
    branches: [main]

jobs:
  eas-build:
    name: Trigger EAS build for development-sim
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repository
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🚀 Send build request
        run: eas build --platform all --non-interactive --no-wait --profile development-sim
        shell: bash
``` 

Here is my `eas.json`
```
{
  "cli": {
    "version": ">= 3.9.2"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "ios": {
        "resourceClass": "m-medium"
      }
    },
    "preview": {
      "distribution": "internal",
      "ios": {
        "resourceClass": "m-medium"
      }
    },
    "production": {
      "env": {
        "SUPABASE_API_URL": ... ,
        "SUPABASE_ANON_KEY": "..."
      },
      "ios": {
        "resourceClass": "m-medium"
      }
    },
    "development-sim": {
      "env": {
        "SUPABASE_API_URL": ... ,
        "SUPABASE_ANON_KEY": "..."
      },
      "distribution": "internal",
      "ios": {
        "simulator": true
      }
    }
  },
  "submit": {
    "production": {}
  }
}
```

Do you have any idea of what can be wrong ?

**Comment by florentpergoud** [comment]
For anyone stumbling on this : 
My mistake was to not change `MaestroEasExample` by my app name: `APP_EXECUTABLE_PATH=/Users/expo/workingdir/build/ios/build/Build/Products/Release-iphonesimulator/YOUR_APP_NAME_HERE.app`

In the `eas-build-on-success.sh`
```

#!/usr/bin/env bash

set -eox pipefail

curl -Ls "https://get.maestro.mobile.dev" | bash
export PATH="$PATH":"$HOME/.maestro/bin"

if [ "$EAS_BUILD_PLATFORM" = "ios" ]
then
   brew install java
   echo 'export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"' >> ~/.zshrc
   sudo ln -sfn /opt/homebrew/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
   export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include"

   APP_EXECUTABLE_PATH=/Users/expo/workingdir/build/ios/build/Build/Products/Release-iphonesimulator/Nouon.app
else
   APP_EXECUTABLE_PATH=/home/expo/workingdir/build/android/app/build/outputs/apk/release/app-release.apk
fi

MAESTRO_API_KEY=$MAESTRO_API_KEY
maestro cloud --apiKey $MAESTRO_API_KEY $APP_EXECUTABLE_PATH maestro/test.yaml  
```
